/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.contarq.appSys;

import br.com.contarq.frame.*;

import java.awt.Dimension;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;

/**
 *
 * @author Usuario
 */
public class App extends javax.swing.JFrame {
    /**
     * Creates new form App
     */
    public App() {
        setUndecorated(true);
        GraphicsDevice gd = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();        
        Dimension dim = new Dimension((int)Toolkit.getDefaultToolkit().getScreenSize().getWidth(), (int)Toolkit.getDefaultToolkit().getScreenSize().getHeight()-39);
        setMinimumSize(dim);
        setMaximumSize(dim);
        initComponents();
        
//        GraphicsDevice gd = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();        
//        Dimension dim = new Dimension((int)Toolkit.getDefaultToolkit().getScreenSize().getWidth(), (int)Toolkit.getDefaultToolkit().getScreenSize().getHeight()-39);
//        setMinimumSize(dim);
//        setMaximumSize(dim);
//        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu7 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jmiConfiguracao = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmiSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiCliente = new javax.swing.JMenuItem();
        jmiFuncionario = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmiPreVenda = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenu7.setText("jMenu7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 731, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );

        jMenuBar1.setMaximumSize(new java.awt.Dimension(200, 25));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(200, 25));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(200, 25));

        jMenu3.setText("  Sistema  ");

        jmiConfiguracao.setText("Configuração");
        jMenu3.add(jmiConfiguracao);
        jMenu3.add(jSeparator1);

        jmiSair.setText("Sair");
        jMenu3.add(jmiSair);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("  Cadastro  ");

        jmiCliente.setText("Cliente");
        jMenu2.add(jmiCliente);

        jmiFuncionario.setText("Funcionário");
        jMenu2.add(jmiFuncionario);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("  Pré-Venda  ");

        jmiPreVenda.setText("Pré-Venda");
        jmiPreVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPreVendaActionPerformed(evt);
            }
        });
        jMenu1.add(jmiPreVenda);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("  Serviços  ");

        jMenuItem1.setText("Controle de Entrega");
        jMenu4.add(jMenuItem1);

        jMenuItem2.setText("Controle de Montagem");
        jMenu4.add(jMenuItem2);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiPreVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPreVendaActionPerformed
        FramePrevenda prevenda = new FramePrevenda(Sys.getLink());
        jDesktopPane1.add(prevenda);
        prevenda.show();
        prevenda.setPosition();
    }//GEN-LAST:event_jmiPreVendaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem jmiCliente;
    private javax.swing.JMenuItem jmiConfiguracao;
    private javax.swing.JMenuItem jmiFuncionario;
    private javax.swing.JMenuItem jmiPreVenda;
    private javax.swing.JMenuItem jmiSair;
    // End of variables declaration//GEN-END:variables
}
